FROM golang:1.25.0-alpine

WORKDIR /app

COPY ingestWorker/go.mod ingestWorker/go.sum ./
RUN go mod download

COPY ingestWorker/. .

RUN go build -o ingestWorker ./cmd/ingestWorker


CMD ["./ingestWorker"]